project_name: changelog

builds:
  - binary: changelog
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "cucumber/{{.ProjectName}}:{{.Tag}}"
      - "cucumber/{{.ProjectName}}:{{ .Major }}"
      - "cucumber/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}"
      - "cucumber/{{.ProjectName}}:latest"
