// Code generated by "stringer -type=ChangeType"; DO NOT EDIT.

package chg

import "strconv"

const _ChangeType_name = "UnknownAddedChangedDeprecatedFixedRemovedSecurity"

var _ChangeType_index = [...]uint8{0, 7, 12, 19, 29, 34, 41, 49}

func (i ChangeType) String() string {
	if i < 0 || i >= ChangeType(len(_ChangeType_index)-1) {
		return "ChangeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChangeType_name[_ChangeType_index[i]:_ChangeType_index[i+1]]
}
